#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://101.200.164.72:3306/gulimall_pms
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 101.200.164.72:8848
#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  mvc:
#    static-path-pattern=/static/**
#  redis:
#    host: 101.200.164.72
#    port: 6379
#
#  application:
#    name: gulimall-product
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#
#server:
#  port: 10001
#
#logging:
#  level:
#    com.atguigu.gulimall: error
#
#
#
