#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 101.200.164.72:8848
#        namespace: gulimall
#    alicloud:
#      access-key: LTAI5tJAWUUDfAvanpTYzT69
#      secret-key: 4lMphGmE4GIDq2X89bNn9dY3rsMi4R
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: gulimall-gaich
#  application:
#    name: gulimall-third-party
#server:
#  port: 30000

